//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_tradingrecord {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txttra_U_ID;
		protected global::System.Web.UI.WebControls.TextBox txttra_transactionAmount;
		protected global::System.Web.UI.WebControls.TextBox txttra_transactionDate;
		protected global::System.Web.UI.WebControls.TextBox txttra_accomplish;
		protected global::System.Web.UI.WebControls.TextBox txttra_staff_id;
		protected global::System.Web.UI.WebControls.TextBox txtsta_comwas_id;
		protected global::System.Web.UI.WebControls.TextBox txttra_number;
	protected global::System.Web.UI.WebControls.Label lbltra_ID;
		protected global::System.Web.UI.WebControls.TextBox txttra_addressID;
		protected global::System.Web.UI.WebControls.TextBox txttra_type;
		protected global::System.Web.UI.WebControls.TextBox txttra_vaild;
		protected global::System.Web.UI.WebControls.TextBox txttra_sort;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
