//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_tradingrecord {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbltra_U_ID;
	protected global::System.Web.UI.WebControls.Label lbltra_transactionAmount;
	protected global::System.Web.UI.WebControls.Label lbltra_transactionDate;
	protected global::System.Web.UI.WebControls.Label lbltra_accomplish;
	protected global::System.Web.UI.WebControls.Label lbltra_staff_id;
	protected global::System.Web.UI.WebControls.Label lblsta_comwas_id;
	protected global::System.Web.UI.WebControls.Label lbltra_number;
	protected global::System.Web.UI.WebControls.Label lbltra_ID;
	protected global::System.Web.UI.WebControls.Label lbltra_addressID;
	protected global::System.Web.UI.WebControls.Label lbltra_type;
	protected global::System.Web.UI.WebControls.Label lbltra_vaild;
	protected global::System.Web.UI.WebControls.Label lbltra_sort;


       
    }
}
