//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_commodity {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcom_ID;
		protected global::System.Web.UI.WebControls.TextBox txtcom_name;
		protected global::System.Web.UI.WebControls.TextBox txtcom_productDate;
		protected global::System.Web.UI.WebControls.TextBox txtcom_number;
		protected global::System.Web.UI.WebControls.TextBox txtcom_strageID;
		protected global::System.Web.UI.WebControls.TextBox txtcom_alertNumber;
		protected global::System.Web.UI.WebControls.TextBox txtcom_pic_ID;
		protected global::System.Web.UI.WebControls.TextBox txtcom_date;
		protected global::System.Web.UI.WebControls.TextBox txtcom_pri_ID;
		protected global::System.Web.UI.WebControls.TextBox txtcom_conversionInt;
		protected global::System.Web.UI.WebControls.TextBox txtcom_comc_ID;
		protected global::System.Web.UI.WebControls.TextBox txtcom_valid;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
