//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_commodity {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcom_ID;
	protected global::System.Web.UI.WebControls.Label lblcom_name;
	protected global::System.Web.UI.WebControls.Label lblcom_productDate;
	protected global::System.Web.UI.WebControls.Label lblcom_number;
	protected global::System.Web.UI.WebControls.Label lblcom_strageID;
	protected global::System.Web.UI.WebControls.Label lblcom_alertNumber;
	protected global::System.Web.UI.WebControls.Label lblcom_pic_ID;
	protected global::System.Web.UI.WebControls.Label lblcom_date;
	protected global::System.Web.UI.WebControls.Label lblcom_pri_ID;
	protected global::System.Web.UI.WebControls.Label lblcom_conversionInt;
	protected global::System.Web.UI.WebControls.Label lblcom_comc_ID;
	protected global::System.Web.UI.WebControls.Label lblcom_valid;


       
    }
}
