//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_waste {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtwas_pic_ID;
	protected global::System.Web.UI.WebControls.Label lblwas_ID;
		protected global::System.Web.UI.WebControls.TextBox txtwas_name;
		protected global::System.Web.UI.WebControls.TextBox txtwas_price;
		protected global::System.Web.UI.WebControls.TextBox txtwas_recoverable;
		protected global::System.Web.UI.WebControls.TextBox txtwas_number;
		protected global::System.Web.UI.WebControls.TextBox txtwas_cate_ID;
		protected global::System.Web.UI.WebControls.TextBox txtwas_valid;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
