//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_news {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtnew_title;
		protected global::System.Web.UI.WebControls.TextBox txtnew_creatDate;
		protected global::System.Web.UI.WebControls.TextBox txtnew_cate_id;
		protected global::System.Web.UI.WebControls.TextBox txtnew_pic_id;
		protected global::System.Web.UI.WebControls.TextBox txtnew_content;
		protected global::System.Web.UI.WebControls.TextBox txtnew_valid;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
