//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_command {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcommand_user_ID;
	protected global::System.Web.UI.WebControls.Label lblcommand_staff_ID;
	protected global::System.Web.UI.WebControls.Label lblcommand_content;
	protected global::System.Web.UI.WebControls.Label lblcommand_ID;
	protected global::System.Web.UI.WebControls.Label lblcommand_Delete;
	protected global::System.Web.UI.WebControls.Label lblcommand_Valid;
	protected global::System.Web.UI.WebControls.Label lblcommand_Date;


       
    }
}
