//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_orderevaluate {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtoe_sort;
		protected global::System.Web.UI.WebControls.TextBox txtoe_vaild;
		protected global::System.Web.UI.WebControls.TextBox txtoe_grade;
		protected global::System.Web.UI.WebControls.TextBox txtoe_isread;
		protected global::System.Web.UI.WebControls.TextBox txtoe_per_type;
		protected global::System.Web.UI.WebControls.TextBox txtoe_content;
		protected global::System.Web.UI.WebControls.TextBox txtoe_tra_id;
		protected global::System.Web.UI.WebControls.TextBox txtoe_per_id;
		protected global::System.Web.UI.WebControls.TextBox txtoe_pic_id;
	protected global::System.Web.UI.WebControls.Label lbloe_id;
		protected global::System.Web.UI.WebControls.TextBox txtoe_date;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
