//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_staff {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtsta_userName;
		protected global::System.Web.UI.WebControls.TextBox txtsta_entryDate;
		protected global::System.Web.UI.WebControls.TextBox txtsta_passWord;
		protected global::System.Web.UI.WebControls.TextBox txtsta_maritalStatus;
		protected global::System.Web.UI.WebControls.TextBox txtsta_IDNumber;
		protected global::System.Web.UI.WebControls.TextBox txtsta_homeAddress;
		protected global::System.Web.UI.WebControls.TextBox txtsta_phone;
		protected global::System.Web.UI.WebControls.TextBox txtsta_name;
		protected global::System.Web.UI.WebControls.TextBox txtsta__pic_id;
		protected global::System.Web.UI.WebControls.TextBox txtsta_tra_id;
		protected global::System.Web.UI.WebControls.TextBox txtsta_lastLogindate;
		protected global::System.Web.UI.WebControls.TextBox txtsta_salary;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
