//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_staff {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblsta_id;
	protected global::System.Web.UI.WebControls.Label lblsta_userName;
	protected global::System.Web.UI.WebControls.Label lblsta_entryDate;
	protected global::System.Web.UI.WebControls.Label lblsta_passWord;
	protected global::System.Web.UI.WebControls.Label lblsta_maritalStatus;
	protected global::System.Web.UI.WebControls.Label lblsta_IDNumber;
	protected global::System.Web.UI.WebControls.Label lblsta_homeAddress;
	protected global::System.Web.UI.WebControls.Label lblsta_phone;
	protected global::System.Web.UI.WebControls.Label lblsta_name;
	protected global::System.Web.UI.WebControls.Label lblsta__pic_id;
	protected global::System.Web.UI.WebControls.Label lblsta_tra_id;
	protected global::System.Web.UI.WebControls.Label lblsta_lastLogindate;
	protected global::System.Web.UI.WebControls.Label lblsta_salary;


       
    }
}
