//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_address {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtadd_u_ID;
		protected global::System.Web.UI.WebControls.TextBox txtadd_contactName;
		protected global::System.Web.UI.WebControls.TextBox txtadd_contactPhone;
		protected global::System.Web.UI.WebControls.TextBox txtadd_date;
		protected global::System.Web.UI.WebControls.TextBox txtadd_postcode;
		protected global::System.Web.UI.WebControls.TextBox txtadd_default;
		protected global::System.Web.UI.WebControls.TextBox txtadd_address;
		protected global::System.Web.UI.WebControls.TextBox txtadd_counties;
		protected global::System.Web.UI.WebControls.TextBox txtadd_city;
		protected global::System.Web.UI.WebControls.TextBox txtadd_province;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
