//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_address {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbladd_u_ID;
	protected global::System.Web.UI.WebControls.Label lbladd_contactName;
	protected global::System.Web.UI.WebControls.Label lbladd_contactPhone;
	protected global::System.Web.UI.WebControls.Label lbladd_date;
	protected global::System.Web.UI.WebControls.Label lbladd_postcode;
	protected global::System.Web.UI.WebControls.Label lbladd_default;
	protected global::System.Web.UI.WebControls.Label lbladd_address;
	protected global::System.Web.UI.WebControls.Label lbladd_counties;
	protected global::System.Web.UI.WebControls.Label lbladd_city;
	protected global::System.Web.UI.WebControls.Label lbladd_province;
	protected global::System.Web.UI.WebControls.Label lbladd_ID;


       
    }
}
