//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_staffsalary {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtSal_absenteeismDay;
		protected global::System.Web.UI.WebControls.TextBox txtsal_bonusM;
		protected global::System.Web.UI.WebControls.TextBox txtsal_describe;
		protected global::System.Web.UI.WebControls.TextBox txtsal_deductM;
		protected global::System.Web.UI.WebControls.TextBox txtsal_totalM;
		protected global::System.Web.UI.WebControls.TextBox txtsal_incrementM;
		protected global::System.Web.UI.WebControls.TextBox txtsal_month;
		protected global::System.Web.UI.WebControls.TextBox txtsal_year;
		protected global::System.Web.UI.WebControls.TextBox txtsal_date;
		protected global::System.Web.UI.WebControls.TextBox txtsal_sta_id;
		protected global::System.Web.UI.WebControls.TextBox txtSal_leaveDay;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
