//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_staffsalary {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblSal_absenteeismDay;
	protected global::System.Web.UI.WebControls.Label lblsal_ID;
	protected global::System.Web.UI.WebControls.Label lblsal_bonusM;
	protected global::System.Web.UI.WebControls.Label lblsal_describe;
	protected global::System.Web.UI.WebControls.Label lblsal_deductM;
	protected global::System.Web.UI.WebControls.Label lblsal_totalM;
	protected global::System.Web.UI.WebControls.Label lblsal_incrementM;
	protected global::System.Web.UI.WebControls.Label lblsal_month;
	protected global::System.Web.UI.WebControls.Label lblsal_year;
	protected global::System.Web.UI.WebControls.Label lblsal_date;
	protected global::System.Web.UI.WebControls.Label lblsal_sta_id;
	protected global::System.Web.UI.WebControls.Label lblSal_leaveDay;


       
    }
}
