//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_systeminterchange {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblsi_sort;
	protected global::System.Web.UI.WebControls.Label lblsi_vaild;
	protected global::System.Web.UI.WebControls.Label lblsi_date;
	protected global::System.Web.UI.WebControls.Label lblsi_content;
	protected global::System.Web.UI.WebControls.Label lblsi_per_type;
	protected global::System.Web.UI.WebControls.Label lblsi_pic_id;
	protected global::System.Web.UI.WebControls.Label lblsi_per_id;
	protected global::System.Web.UI.WebControls.Label lblsi_sl_id;
	protected global::System.Web.UI.WebControls.Label lblsi_id;


       
    }
}
