//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_user {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtu_address;
		protected global::System.Web.UI.WebControls.TextBox txtu_lastLoginDate;
		protected global::System.Web.UI.WebControls.TextBox txtu_creaditsLogID;
		protected global::System.Web.UI.WebControls.TextBox txtu_registrationDate;
	protected global::System.Web.UI.WebControls.Label lblu_ID;
		protected global::System.Web.UI.WebControls.TextBox txtu_nickName;
		protected global::System.Web.UI.WebControls.TextBox txtu_category;
		protected global::System.Web.UI.WebControls.TextBox txtu_birthDate;
		protected global::System.Web.UI.WebControls.TextBox txtu_state;
		protected global::System.Web.UI.WebControls.TextBox txtu_passWord;
		protected global::System.Web.UI.WebControls.TextBox txtu_integral;
		protected global::System.Web.UI.WebControls.TextBox txtu_creditGrade;
		protected global::System.Web.UI.WebControls.TextBox txtu_name;
		protected global::System.Web.UI.WebControls.TextBox txtu_pic_ID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
