//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_user {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblu_address;
	protected global::System.Web.UI.WebControls.Label lblu_lastLoginDate;
	protected global::System.Web.UI.WebControls.Label lblu_creaditsLogID;
	protected global::System.Web.UI.WebControls.Label lblu_registrationDate;
	protected global::System.Web.UI.WebControls.Label lblu_ID;
	protected global::System.Web.UI.WebControls.Label lblu_nickName;
	protected global::System.Web.UI.WebControls.Label lblu_category;
	protected global::System.Web.UI.WebControls.Label lblu_birthDate;
	protected global::System.Web.UI.WebControls.Label lblu_state;
	protected global::System.Web.UI.WebControls.Label lblu_passWord;
	protected global::System.Web.UI.WebControls.Label lblu_integral;
	protected global::System.Web.UI.WebControls.Label lblu_creditGrade;
	protected global::System.Web.UI.WebControls.Label lblu_name;
	protected global::System.Web.UI.WebControls.Label lblu_pic_ID;


       
    }
}
