//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_salarytaxrate {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtSta_threshold;
		protected global::System.Web.UI.WebControls.TextBox txtStr_date;
		protected global::System.Web.UI.WebControls.TextBox txtStr_aged;
		protected global::System.Web.UI.WebControls.TextBox txtStr_medical;
		protected global::System.Web.UI.WebControls.TextBox txtStr_unemployment;
		protected global::System.Web.UI.WebControls.TextBox txtStr_housing;
		protected global::System.Web.UI.WebControls.TextBox txtSta_supplement;
		protected global::System.Web.UI.WebControls.TextBox txtSta_individualTax;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
