//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_salarytaxrate {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblSta_threshold;
	protected global::System.Web.UI.WebControls.Label lblStr_date;
	protected global::System.Web.UI.WebControls.Label lblStr_aged;
	protected global::System.Web.UI.WebControls.Label lblStr_ID;
	protected global::System.Web.UI.WebControls.Label lblStr_medical;
	protected global::System.Web.UI.WebControls.Label lblStr_unemployment;
	protected global::System.Web.UI.WebControls.Label lblStr_housing;
	protected global::System.Web.UI.WebControls.Label lblSta_supplement;
	protected global::System.Web.UI.WebControls.Label lblSta_individualTax;


       
    }
}
