//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_systemleave {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtsl_sort;
		protected global::System.Web.UI.WebControls.TextBox txtsl_valid;
		protected global::System.Web.UI.WebControls.TextBox txtsl_content;
		protected global::System.Web.UI.WebControls.TextBox txtsl_pic_id;
		protected global::System.Web.UI.WebControls.TextBox txtsl_per_id;
	protected global::System.Web.UI.WebControls.Label lblsl_id;
		protected global::System.Web.UI.WebControls.TextBox txtsl_per_type;
		protected global::System.Web.UI.WebControls.TextBox txtsl_date;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
