//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_message {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblmess_ID;
	protected global::System.Web.UI.WebControls.Label lblmess_content;
	protected global::System.Web.UI.WebControls.Label lblmess_date;
	protected global::System.Web.UI.WebControls.Label lblmess_inpotance;
	protected global::System.Web.UI.WebControls.Label lblmess_valid;
	protected global::System.Web.UI.WebControls.Label lblmess_type;


       
    }
}
