//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalleProject.Web.t_staffmenu {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblStaM_User;
	protected global::System.Web.UI.WebControls.Label lblStaM_Boss;
	protected global::System.Web.UI.WebControls.Label lblStaM_Admin;
	protected global::System.Web.UI.WebControls.Label lblStaM_Staff;
	protected global::System.Web.UI.WebControls.Label lblStaM_Url;
	protected global::System.Web.UI.WebControls.Label lblStaM_Name;
	protected global::System.Web.UI.WebControls.Label lblStaM_ID;
	protected global::System.Web.UI.WebControls.Label lblStaM_Delete;
	protected global::System.Web.UI.WebControls.Label lblStaM_MenuClass;
	protected global::System.Web.UI.WebControls.Label lblStaM_Valid;


       
    }
}
